# Generated by Django 3.1.1 on 2020-10-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20201002_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(choices=[('PREMIUM', 'PREMIUM'), ('NOT PREMIUM', 'NOT PREMIUM')], default='PREMIUM', max_length=12),
        ),
    ]
