# Generated by Django 3.1.1 on 2020-11-02 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_coursesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='DateStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
