# Generated by Django 3.1.1 on 2020-11-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_lecturecomment'),
        ('student', '0003_coursesubscription_datestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='progress',
            field=models.CharField(default='0 %', max_length=10),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo', verbose_name='student'),
        ),
    ]
