# Generated by Django 3.1.1 on 2020-11-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201102_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='payment_id',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
