# Generated by Django 3.1.1 on 2020-11-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_course_course_price'),
        ('student', '0005_coursesubscription_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubscription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.course'),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo'),
        ),
    ]
